name: Units CI

on: [push, pull_request]

jobs:
  test:
    name: Unit-Tests QA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run lint
      - run: npm test